### ISSUE TITLE
Emc Dell Unity Vsa 5

### ISSUE THREAD

**Issue by dapiced** [ansible-dellemc-unity/ansible-dellemc-unity#51]
Hi, When i do a  REST remoteSyslog update, it fail with the folowing error:

 "msg": {
        "url": "https://XX.XX.XX.XX/api/instances/remoteSyslog/0?fields=protocol%2Cfacility%2Cenabled%2Caddress&compact=true",
        "error": {
            "errorCode": 131149829,
            "httpStatusCode": 404,
            "messages": [
                {
                    "en-US": "The requested resource does not exist. (Error Code:0x7d13005)"
                }
            ],
            "created": "2019-08-20T14:36:44.960Z"
        }
    }
}

All others ressource is working as expected.... Any Idea ?

**Comment by marsofandrew** [comment]
@dapiced, really I don't know why it happens. Does resource exists? you can check it via Postman or insomnia or any browser. Just send GET request to the instance. 

If issue occurred by our module or your modification for this module, provide some code, please.

**Comment by dapiced** [comment]
> @dapiced, really I don't know why it happens. Does resource exists? you can check it via Postman or insomnia or any browser. Just send GET request to the instance.
> 
> If issue occurred by our module or your modification for this module, provide some code, please.

Hi @marsofandrew , thanks to have replied, i have remove the "id" field in the request and now the ressource has been created....

LIKE THIS ==>
 - {resource_type: remoteSyslog, enabled: True, address: 'XX.XX.XX.XX', protocol: 0, facility: 5}

ps : I did not remove the ID field for the others ressource.... and they did not fail like RemoteSyslog ressource... Only RemoteSyslog fail.... Maybe its because there a default entry for the remotesyslog ressouce and  this entry is not a real entry for REST API...

Dominic

**Comment by marsofandrew** [comment]
Are you create resource (POST) or you update it (PATCH)? If you create resource you shouldn't provide id for it.

**Comment by dapiced** [comment]
It seem that i cannot update the defaut entry for "remotesyslog" ressource (read only field probably, I cannot even delete it from the gui). the only difference between others is that there a default entry, that we can't remove)

hope is clear...

thanks

**Comment by marsofandrew** [comment]
Thanks, can I close the issue?

**Comment by dapiced** [comment]
Yes  !  thanks again to have reply fast !
