### ISSUE TITLE
Cannot create ldapServer ressource

### ISSUE THREAD

**Issue by dapiced** [ansible-dellemc-unity/ansible-dellemc-unity#52]
Hi,  i cannot update the ressource "ldapServer" 👍 

- {resource_type: "ldapServer", authority: "XXX", binDN: "CN=XXX,OU=utilisateur,OU=XXX,OU=XXX,DC=XXX,DC=XXX,DC=XX,DC=XX", bindPassword: "XXX", userSearchPath: "OU=Utilisateur,DC=XX,DC=XX,DC=XX,DC=XX", groupSearchPath: "DC=XX,DC=XX,DC=XX,DC=XX"} 

THE ERROR IS:

 "error": {
            "errorCode": 131149877,
            "httpStatusCode": 422,
            "messages": [
                {
                    "en-US": "Request body is not correct. There may be duplicate parameters, wrong parameter name. Please refer to API documentation page and ensure the body is correct. (Error Code:0x7d13035)"
                }
            ],
            "created": "2019-08-20T18:34:05.853Z"
        }
    }
}

Any idea what wrong ?

thanks
Dominic

**Comment by marsofandrew** [comment]
@dapiced, Have you tried to send the same request via any REST client?

If you ask about Unity REST API, it will take a time to find solution, because, unfortunately, now I haven't any Unity (Unity VSA). I am going to deploy it on September.

**Comment by dapiced** [comment]
yes,  i try with postman, but for some reason, im not able to login with postman

**Comment by marsofandrew** [comment]
You should use both csrf token and basic auth. You can get csrf token by sending any GET request with basic auth authorization

**Comment by dapiced** [comment]
i tried with basic auth, but  Unity return to me with the "user/login page"

i also try bearer auth without succes

**Comment by dapiced** [comment]
I finally been able to login with csrf token, but still having a error

{
    "error": {
        "errorCode": 131150096,
        "httpStatusCode": 400,
        "messages": [
            {
                "en-US": "Invalid request argument: [authority]. (Error Code:0x7d13110)"
            }
        ],
        "created": "2019-08-20T20:11:41.053Z"
    }
}

**Comment by dapiced** [comment]
finaly it was a typo !

binDN:  instead of bindDN:
